//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextCollector.ClientServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientServices.IClientService")]
    public interface IClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/BookSearch", ReplyAction="http://tempuri.org/IClientService/BookSearchResponse")]
        Voodoo.Model.Book[] BookSearch(string str_sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/BookExist", ReplyAction="http://tempuri.org/IClientService/BookExistResponse")]
        bool BookExist(string str_sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/BookFind", ReplyAction="http://tempuri.org/IClientService/BookFindResponse")]
        Voodoo.Model.Book BookFind(string str_sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetBookByID", ReplyAction="http://tempuri.org/IClientService/GetBookByIDResponse")]
        Voodoo.Model.Book GetBookByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/BookInsert", ReplyAction="http://tempuri.org/IClientService/BookInsertResponse")]
        void BookInsert(Voodoo.Model.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/BookUpdate", ReplyAction="http://tempuri.org/IClientService/BookUpdateResponse")]
        void BookUpdate(Voodoo.Model.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/BookDelete", ReplyAction="http://tempuri.org/IClientService/BookDeleteResponse")]
        void BookDelete(string str_sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/ClassSearch", ReplyAction="http://tempuri.org/IClientService/ClassSearchResponse")]
        Voodoo.Model.Class[] ClassSearch(string str_sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/ClassFind", ReplyAction="http://tempuri.org/IClientService/ClassFindResponse")]
        Voodoo.Model.Class ClassFind(string str_sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetClassByID", ReplyAction="http://tempuri.org/IClientService/GetClassByIDResponse")]
        Voodoo.Model.Class GetClassByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/ClassInsert", ReplyAction="http://tempuri.org/IClientService/ClassInsertResponse")]
        void ClassInsert(Voodoo.Model.Class cls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/ClassUpdate", ReplyAction="http://tempuri.org/IClientService/ClassUpdateResponse")]
        void ClassUpdate(Voodoo.Model.Class cls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/ClassDelete", ReplyAction="http://tempuri.org/IClientService/ClassDeleteResponse")]
        void ClassDelete(string str_sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/ChapterSearch", ReplyAction="http://tempuri.org/IClientService/ChapterSearchResponse")]
        Voodoo.Model.BookChapter[] ChapterSearch(string str_sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/ChapterExist", ReplyAction="http://tempuri.org/IClientService/ChapterExistResponse")]
        bool ChapterExist(string str_sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/ChapterFind", ReplyAction="http://tempuri.org/IClientService/ChapterFindResponse")]
        Voodoo.Model.BookChapter ChapterFind(string str_sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetChapterByID", ReplyAction="http://tempuri.org/IClientService/GetChapterByIDResponse")]
        Voodoo.Model.BookChapter GetChapterByID(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/ChapterInsert", ReplyAction="http://tempuri.org/IClientService/ChapterInsertResponse")]
        void ChapterInsert(Voodoo.Model.BookChapter chapter, string Content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/ChapterUpdate", ReplyAction="http://tempuri.org/IClientService/ChapterUpdateResponse")]
        void ChapterUpdate(Voodoo.Model.BookChapter chapter, string Content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/ChapterDelete", ReplyAction="http://tempuri.org/IClientService/ChapterDeleteResponse")]
        void ChapterDelete(string str_sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/CreateIndex", ReplyAction="http://tempuri.org/IClientService/CreateIndexResponse")]
        void CreateIndex();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/CreateClassPage", ReplyAction="http://tempuri.org/IClientService/CreateClassPageResponse")]
        void CreateClassPage();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientServiceChannel : TextCollector.ClientServices.IClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceClient : System.ServiceModel.ClientBase<TextCollector.ClientServices.IClientService>, TextCollector.ClientServices.IClientService {
        
        public ClientServiceClient() {
        }
        
        public ClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Voodoo.Model.Book[] BookSearch(string str_sql) {
            return base.Channel.BookSearch(str_sql);
        }
        
        public bool BookExist(string str_sql) {
            return base.Channel.BookExist(str_sql);
        }
        
        public Voodoo.Model.Book BookFind(string str_sql) {
            return base.Channel.BookFind(str_sql);
        }
        
        public Voodoo.Model.Book GetBookByID(int id) {
            return base.Channel.GetBookByID(id);
        }
        
        public void BookInsert(Voodoo.Model.Book book) {
            base.Channel.BookInsert(book);
        }
        
        public void BookUpdate(Voodoo.Model.Book book) {
            base.Channel.BookUpdate(book);
        }
        
        public void BookDelete(string str_sql) {
            base.Channel.BookDelete(str_sql);
        }
        
        public Voodoo.Model.Class[] ClassSearch(string str_sql) {
            return base.Channel.ClassSearch(str_sql);
        }
        
        public Voodoo.Model.Class ClassFind(string str_sql) {
            return base.Channel.ClassFind(str_sql);
        }
        
        public Voodoo.Model.Class GetClassByID(int id) {
            return base.Channel.GetClassByID(id);
        }
        
        public void ClassInsert(Voodoo.Model.Class cls) {
            base.Channel.ClassInsert(cls);
        }
        
        public void ClassUpdate(Voodoo.Model.Class cls) {
            base.Channel.ClassUpdate(cls);
        }
        
        public void ClassDelete(string str_sql) {
            base.Channel.ClassDelete(str_sql);
        }
        
        public Voodoo.Model.BookChapter[] ChapterSearch(string str_sql) {
            return base.Channel.ChapterSearch(str_sql);
        }
        
        public bool ChapterExist(string str_sql) {
            return base.Channel.ChapterExist(str_sql);
        }
        
        public Voodoo.Model.BookChapter ChapterFind(string str_sql) {
            return base.Channel.ChapterFind(str_sql);
        }
        
        public Voodoo.Model.BookChapter GetChapterByID(long id) {
            return base.Channel.GetChapterByID(id);
        }
        
        public void ChapterInsert(Voodoo.Model.BookChapter chapter, string Content) {
            base.Channel.ChapterInsert(chapter, Content);
        }
        
        public void ChapterUpdate(Voodoo.Model.BookChapter chapter, string Content) {
            base.Channel.ChapterUpdate(chapter, Content);
        }
        
        public void ChapterDelete(string str_sql) {
            base.Channel.ChapterDelete(str_sql);
        }
        
        public void CreateIndex() {
            base.Channel.CreateIndex();
        }
        
        public void CreateClassPage() {
            base.Channel.CreateClassPage();
        }
    }
}
